// <auto-generated />
using System;
using IceTube;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IceTube.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180627140247_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("IceTube.DataModels.GoogleDataStoreObject", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<string>("SourceType");

                    b.HasKey("Key");

                    b.ToTable("GoogleDataStores");
                });

            modelBuilder.Entity("IceTube.DataModels.IceTubeTask", b =>
                {
                    b.Property<string>("TaskName")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("LastRan");

                    b.Property<string>("LastRanStatus");

                    b.Property<bool?>("LastRanSuccess");

                    b.HasKey("TaskName");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("IceTube.DataModels.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime>("LastCheckedAt");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
